import type { FeatureShowcaseEntry } from '@/lib/types'

export const featureEntries: FeatureShowcaseEntry[] = [
  {
    slug: 'planning-goals',
    title: 'Planning / goal abstraction',
    summary: 'Ordered phases, local-date deadlines, and recommendation roles let consumer apps turn progress counts into a clear next track.',
    modules: ['goal'],
    exampleKind: 'state-machine',
    docsHref: '/docs/planning-goals',
    whenToUse: [
      'You need a launcher or dashboard to pick the primary study track.',
      'You want deadline-aware catch-up behavior without pushing learner DB concerns into the core.',
      'You need one plan format that can work for concepts, sections, or unit rollups.',
    ],
    primarySnippetSource: {
      filePath: 'src/goal/index.ts',
      language: 'ts',
      title: 'Goal types and evaluation helpers',
      start: 'export type GoalDeadlineBehavior =',
      end: 'export const DEFAULT_GOAL_DEADLINE_BEHAVIOR: GoalDeadlineBehavior = \'stay_primary_until_complete\'',
    },
    consumerExample: {
      repo: 'stats-exam-prep-game',
      label: 'Stats goal dashboard adapter',
      summary: 'Stats converts concept snapshots into phase snapshots and leaves grade math plus launcher copy local.',
      snippetId: 'stats-study-goal-plan',
    },
  },
  {
    slug: 'scheduler',
    title: 'Scheduler',
    summary: 'Concept-level mastery math, spacing, and next-concept selection stay policy-driven so each game can own its own UI and gating rules.',
    modules: ['scheduler', 'concept'],
    exampleKind: 'state-machine',
    docsHref: '/docs/scheduler',
    whenToUse: [
      'You need to keep struggling concepts near the front without abandoning spaced repetition.',
      'You want support, failure, and retention logic to be deterministic and testable.',
      'You want consumer apps to supply eligibility and prerequisite rules without forking the scheduler.',
    ],
    primarySnippetSource: {
      filePath: 'src/scheduler/index.ts',
      language: 'ts',
      title: 'Scheduler policy and state',
      start: 'export type PracticeOutcome =',
      end: 'export function buildInitialConceptSchedule<TSubskill extends string = string>(',
    },
  },
  {
    slug: 'workflow-core',
    title: 'Workflow session / persistence / debug',
    summary: 'The workflow layer defines the state and persistence contracts consumer shells use for session routing, restore, and deterministic debug forcing.',
    modules: ['workflow/session', 'workflow/debug', 'workflow/quiz-engine'],
    exampleKind: 'consumer-flow',
    docsHref: '/docs/workflow-core',
    whenToUse: [
      'You need stable storage keys and snapshots for quiz sessions.',
      'You need deterministic `wf=1` routes for regression and browser debugging.',
      'You need lightweight state helpers for staged-answer and support flows.',
    ],
    primarySnippetSource: {
      filePath: 'src/workflow/session.ts',
      language: 'ts',
      title: 'Session identity and snapshot helpers',
      start: 'export interface SessionIdentity {',
      end: 'export function isSessionSnapshot<TState extends Record<string, unknown> = Record<string, unknown>>(',
    },
  },
  {
    slug: 'wf-harness',
    title: 'WF harness',
    summary: 'The harness validates static well-formedness across question coverage, payload shape, concept wiring, generator determinism, and scheduler scenarios.',
    modules: ['wf-harness', 'scheduler', 'generator'],
    exampleKind: 'code-snippet',
    docsHref: '/docs/wf-harness',
    whenToUse: [
      'You want fast contract checks before running browser regression.',
      'You need a reusable validator layer across multiple review-game repos.',
      'You want scheduler transitions and selection scenarios locked down in code.',
    ],
    primarySnippetSource: {
      filePath: 'src/wf-harness/validators.ts',
      language: 'ts',
      title: 'WF harness config surface',
      start: 'export interface WFHarnessPayloadSpec {',
      end: 'export const WF_GROUP_NAMES = {',
    },
  },
  {
    slug: 'graph-subsystem',
    title: 'Graph contracts / query / projector',
    summary: 'The graph layer projects authored learning structure into Neo4j as a rebuildable read model instead of turning the graph into an operational source of truth.',
    modules: ['graph/contracts', 'graph/query', 'graph/projector'],
    exampleKind: 'code-snippet',
    docsHref: '/docs/graph-subsystem',
    whenToUse: [
      'You need canonical concepts, ladders, objectives, and artifacts outside the app runtime.',
      'You want projection-first read models rather than a graph-owned content system.',
      'You need typed query shapes over Neo4j data.',
    ],
    primarySnippetSource: {
      filePath: 'src/graph/contracts/index.ts',
      language: 'ts',
      title: 'Projection contracts',
      start: 'export const GRAPH_SCHEMA_VERSION = 1',
      end: 'export const graphQuestionTargetsStepProjectionSchema = z.object({',
    },
  },
  {
    slug: 'question-generator-primitives',
    title: 'Concept tree + question / generator primitives',
    summary: 'Questions, concepts, and seeded generators stay minimal so consumer repos can shape content and rendering without fighting a heavyweight framework.',
    modules: ['question', 'concept', 'generator'],
    exampleKind: 'code-snippet',
    docsHref: '/docs/quick-start',
    whenToUse: [
      'You want shared type contracts across multiple games.',
      'You need deterministic seeded generators for repeatable variants.',
      'You want concept trees to drive prerequisite and mastery logic without a UI dependency.',
    ],
    primarySnippetSource: {
      filePath: 'src/concept/index.ts',
      language: 'ts',
      title: 'Concept tree primitives',
      start: 'export interface ConceptNode {',
      end: 'export function getNextUnlockedConcepts(',
    },
  },
]
