import type { FeatureShowcaseEntry } from '@/lib/types'

export const featureEntries: FeatureShowcaseEntry[] = [
  {
    slug: 'planning-goals',
    title: 'Planning / goal abstraction',
    summary: 'Ordered phases, local-date deadlines, and recommendation roles let consumer apps turn progress counts into a clear next track.',
    modules: ['goal'],
    exampleKind: 'state-machine',
    docsHref: '/docs/planning-goals',
    whenToUse: [
      'You need a launcher or dashboard to pick the primary study track.',
      'You want deadline-aware catch-up behavior without pushing learner DB concerns into the core.',
      'You need one plan format that can work for concepts, sections, or unit rollups.',
    ],
    primarySnippetSource: {
      filePath: 'src/goal/index.ts',
      language: 'ts',
      title: 'Goal types and evaluator',
      start: 'export type GoalDeadlineBehavior =',
      end: 'export function buildGoalPhaseStates<TTrackId extends string>(',
    },
    consumerExample: {
      repo: 'stats-exam-prep-game',
      label: 'Stats goal dashboard adapter',
      summary: 'Stats converts concept snapshots into phase snapshots and leaves grade math plus launcher copy local.',
      snippetId: 'stats-study-goal-plan',
    },
  },
  {
    slug: 'scheduler',
    title: 'Scheduler',
    summary: 'Concept-level mastery math, spacing, and next-concept selection stay policy-driven so each game can own its own UI and gating rules.',
    modules: ['scheduler', 'concept'],
    exampleKind: 'state-machine',
    docsHref: '/docs/scheduler',
    whenToUse: [
      'You need to keep struggling concepts near the front without abandoning spaced repetition.',
      'You want support, failure, and retention logic to be deterministic and testable.',
      'You want consumer apps to supply eligibility and prerequisite rules without forking the scheduler.',
    ],
    primarySnippetSource: {
      filePath: 'src/scheduler/base.ts',
      language: 'ts',
      title: 'Scheduler state and outcome transitions',
      start: 'export function buildInitialConceptSchedule<TSubskill extends string = string>(',
      end: 'export function applySupplementalConceptExposure<TSubskill extends string = string>(',
    },
  },
  {
    slug: 'guided-repetition',
    title: 'Guided repetition ladder',
    summary: 'Concept-first rep phases — light, hard, and recovery-light — with explicit attempt budgets and selection reasons so apps can teach first, then fade to independent proof.',
    modules: ['scheduler', 'concept'],
    exampleKind: 'state-machine',
    docsHref: '/docs/scheduler',
    whenToUse: [
      'You want a shared rep ladder instead of a per-game ad-hoc retry loop.',
      'You need deterministic hard-attempt budgets and recovery-light counts.',
      'You want a named selection reason (new concept, guided mastery, recovery due, retention due, weakest subskill) the UI can show without inventing its own.',
    ],
    primarySnippetSource: {
      filePath: 'src/scheduler/guided.ts',
      language: 'ts',
      title: 'Repetition phases, attempt budgets, and selection reasons',
      start: 'export type RepetitionPhase =',
      end: 'const isRecord = (value: unknown): value is Record<string, unknown> => (',
    },
  },
  {
    slug: 'readiness-truthfulness',
    title: 'Readiness scoring and phase state',
    summary: 'A coarse 0–100 readiness signal and a six-value phase vocabulary (not_started, learning, practicing, mastered, shaky, tracked_in_quiz) that products can roll up without overclaiming.',
    modules: ['readiness', 'scheduler/phase-state'],
    exampleKind: 'code-snippet',
    docsHref: '/docs/scheduler',
    whenToUse: [
      'You need a single routing-friendly score per unit plus a rollup across children.',
      'You want phase labels that map cleanly to launcher copy without implying psychometric precision.',
      'You need the core to stay honest about what the score is — a recommendation signal, not an assessment.',
    ],
    primarySnippetSource: {
      filePath: 'src/readiness/index.ts',
      language: 'ts',
      title: 'Readiness types, phase baselines, and aggregation',
      start: 'export type ReadinessScore =',
      end: 'export const aggregateReadiness = (children: ReadinessScore[]): ReadinessScore => {',
    },
  },
  {
    slug: 'workflow-core',
    title: 'Workflow quiz engine / session / debug',
    summary: 'The quiz engine runs a turn through six phases; session and debug helpers let consumer shells persist and force routes deterministically.',
    modules: ['workflow/quiz-engine', 'workflow/session', 'workflow/debug'],
    exampleKind: 'consumer-flow',
    docsHref: '/docs/workflow-core',
    whenToUse: [
      'You want a reducer-friendly six-phase turn engine.',
      'You need stable storage keys and snapshots for quiz sessions.',
      'You need deterministic `wf=1` routes for regression and browser debugging.',
      'You need lightweight state helpers for staged-answer and support flows.',
    ],
    primarySnippetSource: {
      filePath: 'src/workflow/quiz-engine.ts',
      language: 'ts',
      title: 'Quiz engine phases and transitions',
      start: 'export type QuizEnginePhase =',
      end: 'export function resetQuizEngine<TQuestion extends QuizEngineQuestion = QuizEngineQuestion>(',
    },
  },
  {
    slug: 'content-identity-restore',
    title: 'Content-identity restore seam',
    summary: 'Session snapshots carry an optional content identity (questionId, contentId, contentVersion) so a restored turn can be compared honestly against current authored content before it is resumed.',
    modules: ['workflow/session', 'workflow/persistence'],
    exampleKind: 'code-snippet',
    docsHref: '/docs/workflow-core',
    whenToUse: [
      'You persist in-progress quiz turns and need to know whether the authored question drifted.',
      'You want one shared comparison shape (matches, mismatchFields, unknownFields) instead of per-game invalidation heuristics.',
      'You want the core to expose the seam while each consumer picks its own invalidation policy.',
    ],
    primarySnippetSource: {
      filePath: 'src/workflow/session.ts',
      language: 'ts',
      title: 'Content identity types and comparison contract',
      start: 'export type SessionContentVersion =',
      end: 'export interface SessionSnapshotFactoryOptions {',
    },
  },
  {
    slug: 'workflow-interventions',
    title: 'Per-question experiment gating',
    summary: 'Deterministic cohort resolution, exposure records, and served-question metadata for experimental or LLM-variant questions — so gated content stays visible, auditable, and WF-testable before it reaches learners.',
    modules: ['workflow/interventions'],
    exampleKind: 'code-snippet',
    docsHref: '/docs/workflow-core',
    whenToUse: [
      'You want experimental or LLM-authored variants to ride the same turn engine as canonical questions.',
      'You need a deterministic resolution key so a learner sees the same arm on the same turn across reloads.',
      'You want served-question metadata (experimentKey, experimentArm, sourceQuestionId, questionOrigin) that WF can gate on before exposure.',
    ],
    primarySnippetSource: {
      filePath: 'src/workflow/interventions.ts',
      language: 'ts',
      title: 'Intervention cohort resolution and exposure contracts',
      start: 'export type WorkflowInterventionCohortMode =',
      end: 'const isNonEmptyString = (value: unknown): value is string => (',
    },
  },
  {
    slug: 'wf-harness',
    title: 'WF harness',
    summary: 'The harness validates static well-formedness across question coverage, payload shape, concept wiring, generator determinism, and scheduler scenarios.',
    modules: ['wf-harness', 'scheduler', 'generator'],
    exampleKind: 'code-snippet',
    docsHref: '/docs/wf-harness',
    whenToUse: [
      'You want fast contract checks before running browser regression.',
      'You need a reusable validator layer across multiple review-game repos.',
      'You want scheduler transitions and selection scenarios locked down in code.',
    ],
    primarySnippetSource: {
      filePath: 'src/wf-harness/validators.ts',
      language: 'ts',
      title: 'WF harness config and a validator',
      start: 'export interface WFHarnessPayloadSpec {',
      end: 'export function validateGeneratorDeterminism<TType extends string, TSubskill extends string = string>(',
    },
  },
  {
    slug: 'graph-subsystem',
    title: 'Graph contracts / query / projector',
    summary: 'The graph layer projects authored learning structure into Neo4j as a rebuildable read model instead of turning the graph into an operational source of truth.',
    modules: ['graph/contracts', 'graph/query', 'graph/projector'],
    exampleKind: 'code-snippet',
    docsHref: '/docs/graph-subsystem',
    whenToUse: [
      'You need canonical concepts, ladders, objectives, and artifacts outside the app runtime.',
      'You want projection-first read models rather than a graph-owned content system.',
      'You need typed query shapes over Neo4j data.',
    ],
    primarySnippetSource: {
      filePath: 'src/graph/contracts/index.ts',
      language: 'ts',
      title: 'Projection contracts',
      start: 'export const GRAPH_SCHEMA_VERSION = 1',
      end: 'export const graphQuestionTargetsStepProjectionSchema = z.object({',
    },
  },
  {
    slug: 'question-generator-primitives',
    title: 'Concept tree + question / generator primitives',
    summary: 'Questions, concepts, and seeded generators stay minimal so consumer repos can shape content and rendering without fighting a heavyweight framework — with room for a concept-first rubric (disclosure, scaffold-then-fade) above the core types.',
    modules: ['question', 'concept', 'generator'],
    exampleKind: 'code-snippet',
    docsHref: '/docs/quick-start',
    whenToUse: [
      'You want shared type contracts across multiple games.',
      'You need deterministic seeded generators for repeatable variants.',
      'You want concept trees to drive prerequisite and mastery logic without a UI dependency.',
      'You want a shared authoring rubric to hang on top of the contract instead of re-inventing scaffold or disclosure rules per repo.',
    ],
    primarySnippetSource: {
      filePath: 'src/concept/index.ts',
      language: 'ts',
      title: 'Concept tree primitives',
      start: 'export interface ConceptNode {',
      end: 'export function getNextUnlockedConcepts(',
    },
  },
]
